project_name: terraform-provider-gitlab

builds:
  - binary: "terraform-provider-gitlab_{{.Tag}}"
    goos:
      - freebsd
      - windows
      - linux
      - solaris
      - openbsd
      - darwin
    goarch:
      - amd64
      - 386
      - arm
    ignore:
      - goos: darwin
        goarch: 386
      - goos: solaris
        goarch: 386
      - goos: darwin
        goarch: arm
      - goos: openbsd
        goarch: arm
      - goos: windows
        goarch: arm
      - goos: solaris
        goarch: arm
      - goos: freebsd
        goarch: arm

archives:
  - format: zip
    files:
      - none*

release:
  github:
    owner: claranet
    name: terraform-provider-gitlab
